---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: PFA2021
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: projectflask
        image:  essole/pfa2021:1.0.0
        ports:
        - containerPort: 5000
      - name: Ngenix
        image:  essole/linkextractor-web:v1-php
        ports:
        - containerPort: 85
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: devopsproject
spec:
  selector:
    app: web
  ports:
  - name: apiport
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: webport
    protocol: TCP
    port: 8081
    targetPort: 80
