---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: pfa2021
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: projectflask
        image:  essole/pfa2021:1.0.0
        ports:
        - containerPort: 5005
      - name: nginx
        image:  nginx:latest
        ports:
        - containerPort: 85
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: pfa2021
spec:
  selector:
    app: web
  ports:
  - name: apiport
    protocol: TCP
    port: 5005
    targetPort: 5005
  - name: webport
    protocol: TCP
    port: 85
    targetPort: 85
